<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CSharpVN_Community</RootNamespace>
    <UserSecretsId>1565ef1b-56db-44db-82d4-442566bc00b3</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Supabase" Version="1.1.1" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if $(ConfigurationName) == Debug (&#xD;&#xA;   git add .&#xD;&#xA;   git commit -m &quot;Auto-build Debug $(DateTime)&quot;&#xD;&#xA;   git push&#xD;&#xA;)" />
  </Target>

</Project>
